-- Run once at compositor start (exec-once equivalent)
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl output create headless && systemctl --user restart sunshine")
    hl.exec_cmd("~/.config/hypr/scripts/set-wallpaper")
    hl.exec_cmd("env QT_QPA_PLATFORMTHEME=gtk3 quickshell &")
    hl.exec_cmd("nm-applet --indicator &")
    hl.exec_cmd("udiskie &")
    hl.exec_cmd("systemctl --user import-environment &")
    hl.exec_cmd("hash dbus-update-activation-environment 2>/dev/null &")
    hl.exec_cmd("dbus-update-activation-environment --systemd &")
    hl.exec_cmd("clipse --listen")
end)

-- Runs on every config load (exec equivalent)
hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
