$blue = rgba(89b4faff)
$lavender = rgba(b4befeff)
$teal = rgba(94e2d5ff)
$green = rgba(a6e3a1ff)
$mauve = rgba(cba6f7ff)
$surface0 = rgba(313244ff)
$surface1 = rgba(45475aff)
$mantle = rgba(181825ff)
$crust = rgba(11111bff)
$text = rgba(cdd6f4ff)
