-- Cursor sizes (envd in hyprlang -> also propagated to dbus/systemd)
hl.env("HYPRCURSOR_SIZE", "24", true)
hl.env("XCURSOR_SIZE",    "24", true)
hl.env("QT_CURSOR_SIZE",  "24", true)

hl.env("LIBVA_DRIVER_NAME",          "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME",  "nvidia")
hl.env("NVD_BACKEND",                "direct")
hl.env("AQ_DRM_DEVICES",             "/dev/dri/card1")
hl.env("XDG_SESSION_TYPE",           "wayland")
hl.env("GBM_BACKEND",                "nvidia-drm")
hl.env("SDL_VIDEODRIVER",            "wayland")
hl.env("MOZ_DISABLE_RDD_SANDBOX",    "1")
hl.env("EGL_PLATFORM",               "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORMTHEME",         "qt6ct")
hl.env("QT_QPA_PLATFORM",              "wayland")
hl.env("QT_STYLE_OVERRIDE",            "kvantum-dark")
hl.env("GTK_THEME",                    "catppuccin-mocha-blue-standard+default")
