source = ~/.config/hypr/config/colors.conf

general {
    gaps_in = 3
    gaps_out = 5
    border_size = 3
    col.active_border = $blue
    col.inactive_border = $surface0
    layout = dwindle

    snap {
    	enabled = true
    }
}

group {
	col.border_active = $teal
	col.border_inactive = $surface1
	col.border_locked_active = $green
	col.border_locked_inactive = $crust

	groupbar {
		font_family = "JetBrainsMono Nerd Font"
		text_color = $text
		col.active = $teal
		col.inactive = $surface1
		col.locked_active = $green
		col.locked_inactive = $crust
	}
}

misc {
    font_family = "JetBrainsMono Nerd Font"
    splash_font_family = "JetBrainsMono Nerd Font"
    disable_hyprland_logo = true
    col.splash = $blue
    background_color = $crust
    enable_swallow = true
    swallow_regex = ^(firefox|nautilus|nemo|thunar)$
    focus_on_activate = true
    vrr = 2
}

render {
   direct_scanout = true
}

dwindle {
    special_scale_factor = 0.8
preserve_split = true
}

master {
    new_status = master
    special_scale_factor = 0.8
}
