windowrule = match:class = ^(clipse)$, float = yes, size = 622 652, move = center
windowrule = match:class = ^(org.pulseaudio.pavucontrol), float = yes
windowrule = match:title = ^(Picture in picture)$, float = yes
windowrule = match:title = ^(Save File)$, float = yes
windowrule = match:title = ^(Open File)$, float = yes
windowrule = match:class = ^(LibreWolf)$, match:title = ^(Picture-in-Picture)$, float = yes
windowrule = match:class = ^(blueman-manager)$, float = yes
windowrule = match:class = ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$, float = yes
windowrule = match:class = ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$, float = yes
windowrule = match:class = ^(zenity)$, float = yes
windowrule = match:title = ^(Steam - Self Updater)$, float = yes

windowrule = match:class = ^(thunar|nemo)$, opacity 0.92
windowrule = match:class = ^(discord|armcord|webcord)$, opacity 0.96
windowrule = match:title = ^(QQ|Telegram)$, opacity 0.95
windowrule = match:title = ^(NetEase Cloud Music Gtk4)$, opacity 0.95

windowrule = match:title = ^(Picture-in-Picture)$, float = yes, size = 960 540, move = 25%-
windowrule = match:title = ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$, float = yes, size = 960 540, move = 25%-
windowrule = match:title = ^(danmufloat)$, pin = yes
windowrule = match:title = ^(danmufloat|termfloat)$, rounding 5
windowrule = match:class = ^(kitty|Alacritty)$, animation = slide right
windowrule = match:class = ^(org.mozilla.firefox)$, no_blur = yes

windowrule = match:float = true, match:workspace = w[fv1-10], border_size 2, border_color rgb(89b4fa), rounding 8
windowrule = match:float = false, match:workspace = f[1-10], border_size 3, rounding 4

workspace = w[tv1-10], gapsout:5, gapsin:3
workspace = f[1], gapsout:5, gapsin:3

layerrule = match:namespace = logout_dialog, animation = slide top
layerrule = match:namespace = waybar, animation = slide down
layerrule = match:namespace = quickshell, animation = slide down
layerrule = match:namespace = wallpaper, animation = fade 50%
